# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cma_model_params import CMAModelParams

class TestCMAModelParams(unittest.TestCase):
    """CMAModelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CMAModelParams:
        """Test CMAModelParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CMAModelParams`
        """
        model = CMAModelParams()
        if include_optional:
            return CMAModelParams(
                t = 1.337,
                n = 56,
                d = 1.337,
                taup = 1.337,
                taug = 1.337,
                b = 1.337,
                cm = 1.337,
                toff = 1.337,
                t_m = None,
                seed = None,
                eps = 1.337,
                lb = None,
                ub = None,
                bounded_param_keys = None,
                midbound = None,
                bounded_param_descriptions = None,
                bounds = openapi_client.models.cma_model_params_bounds.CMAModelParams_bounds(
                    lb = [
                        1.337
                        ], 
                    ub = [
                        1.337
                        ], 
                    keep_feasible = [
                        True
                        ], )
            )
        else:
            return CMAModelParams(
        )
        """

    def testCMAModelParams(self):
        """Test CMAModelParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
