# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bounded_param_descriptions import BoundedParamDescriptions

class TestBoundedParamDescriptions(unittest.TestCase):
    """BoundedParamDescriptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoundedParamDescriptions:
        """Test BoundedParamDescriptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoundedParamDescriptions`
        """
        model = BoundedParamDescriptions()
        if include_optional:
            return BoundedParamDescriptions(
            )
        else:
            return BoundedParamDescriptions(
        )
        """

    def testBoundedParamDescriptions(self):
        """Test BoundedParamDescriptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
