# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_default_params_params_default_get(self) -> None:
        """Test case for default_params_params_default_get

        Default Params
        """
        pass

    def test_fit_model_to_data_fit_post(self) -> None:
        """Test case for fit_model_to_data_fit_post

        Fit Model To Data
        """
        pass

    def test_get_sample_dataset_data_sample_get(self) -> None:
        """Test case for get_sample_dataset_data_sample_get

        Get Sample Dataset
        """
        pass

    def test_params_schema_params_schema_get(self) -> None:
        """Test case for params_schema_params_schema_get

        Params Schema
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_run_at_time_route_run_at_time_post(self) -> None:
        """Test case for run_at_time_route_run_at_time_post

        Run At Time Route
        """
        pass

    def test_run_model_run_post(self) -> None:
        """Test case for run_model_run_post

        Run Model
        """
        pass

    def test_translate_model_results_by_language_translate_results_post(self) -> None:
        """Test case for translate_model_results_by_language_translate_results_post

        Translate Model Results By Language
        """
        pass


if __name__ == '__main__':
    unittest.main()
