apiVersion: v1
kind: Service
metadata:
  annotations:
    compose2nix.settings.sops.secrets: .env
    kompose.cmd: kompose convert -c -o pfun-cma-model-chart
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: pfun-cma-model
  name: pfun-cma-model
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: pfun-cma-model
