services:
  pfun-cma-model:
    restart: unless-stopped
    # Comment the develop/watch section out for compatibility with **podman-compose**:
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
          ignore:
            - .git/
            - .trunk/
            - pfun-cma-model.code-workspace
            - poetry.lock
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - dexcom_api_client_id
        - dexcom_api_secret
        - secret_key
        - gemini_api_key
    user: "nonroot:nonroot"
    env_file: .env
    environment:
      - USER=nonroot
      - GROUP=nonroot
      - DEXCOM_API_CLIENT_ID=/run/secrets/dexcom_api_client_id
      - DEXCOM_API_SECRET=/run/secrets/dexcom_api_secret
      - SECRET_KEY=/run/secrets/secret_key
      - GEMINI_API_KEY=/run/secrets/gemini_api_key
    container_name: pfun-cma-model
    ports:
      - "8001:8001"
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "pfun_cma_model.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--workers",
        "1",
      ]
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--save",
        "60",
        "1",
        "--appendonly",
        "no",
        "--loglevel",
        "warning",
      ]

  postgres:
    image: "postgres:16-alpine"
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: pfun
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pfun_cma_model_data:/var/lib/postgresql/data

volumes:
  pfun_cma_model_data:

secrets:
  gemini_api_key:
    environment: GEMINI_API_KEY
  dexcom_api_client_id:
    environment: DEXCOM_API_CLIENT_ID
  dexcom_api_secret:
    environment: DEXCOM_API_SECRET
  secret_key:
    environment: SECRET_KEY
  postgres_password:
    environment: POSTGRES_PASSWORD
