services:

  pfun-cma-model:
    restart: unless-stopped
    # # Commented this out for compatibility with podman-compose
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
          ignore:
            - .git/
            - .trunk/
            - pfun-cma-model.code-workspace
            - poetry.lock
    build:
      context: .
      dockerfile: Dockerfile
    user: "nonroot:nonroot"
    environment:
      - USER=nonroot
      - GROUP=nonroot
    container_name: pfun-cma-model
    ports:
      - "8001:8001"
    command: [
      "uv", "run","uvicorn",
      "pfun_cma_model.app:app",
      "--host", "0.0.0.0",
      "--port", "8001",
      "--workers", "1"
    ]

  # pfun-cma-mcp-server:
  #   depends_on:
  #     - redis
  #     - pfun-cma-model
  #   container_name: pfun-cma-mcp-server
  #   restart: unless-stopped
  #   build:
  #     context: ./pfun-cma-mcp-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   command: ["npm", "run", "start"]

  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: [
      "redis-server", 
      "--save", "60", "1", 
      "--appendonly", "no",
      "--loglevel", "warning"
      ]