services:

  pfun-cma-model:
    restart: unless-stopped
    # Comment the develop/watch section out for compatibility with **podman-compose**:
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
          ignore:
            - .git/
            - .trunk/
            - pfun-cma-model.code-workspace
            - poetry.lock
    build:
      context: .
      dockerfile: Dockerfile
    user: "nonroot:nonroot"
    environment:
      - USER=nonroot
      - GROUP=nonroot
    container_name: pfun-cma-model
    ports:
      - "8001:8001"
    command: [
      "uv", "run","uvicorn",
      "pfun_cma_model.app:app",
      "--host", "0.0.0.0",
      "--port", "8001",
      "--workers", "1"
    ]
    depends_on:
      - redis

  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: [
      "redis-server", 
      "--save", "60", "1", 
      "--appendonly", "no",
      "--loglevel", "warning"
      ]