services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "nonroot:nonroot"
    environment:
      - USER=nonroot
      - GROUP=nonroot
    image: pfun-cma-model:latest
    container_name: pfun-cma-model
    ports:
      - "8001:8001"
    command:
      [
        "/home/nonroot/.local/bin/uvicorn",
        "pfun_cma_model.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--workers",
        "2"
      ]
