version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "nonroot:nonroot"
    environment:
      - USER=nonroot
      - GROUP=nonroot
    image: pfun-cma-model:latest
    container_name: pfun-cma-model
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command:
      [
        "/usr/bin/env",
        "/bin/bash",
        "-ce",
        "python",
        "-m",
        "uvicorn",
        "pfun_cma_model.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
