services:
  pfun-cma-model:
    restart: unless-stopped
    # Comment the develop/watch section out for compatibility with **podman-compose**:
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
          ignore:
            - .git/
            - .trunk/
            - pfun-cma-model.code-workspace
            - poetry.lock
    build:
      context: .
      dockerfile: Dockerfile
    user: "nonroot:nonroot"
    env_file: .env
    environment:
      - USER=nonroot
      - GROUP=nonroot
    container_name: pfun-cma-model
    ports:
      - "8001:8001"
    command: [
      "uv", "run","uvicorn",
      "pfun_cma_model.app:app",
      "--host", "0.0.0.0",
      "--port", "8001",
      "--workers", "1"
    ]
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: [
      "redis-server", 
      "--save", "60", "1", 
      "--appendonly", "no",
      "--loglevel", "warning"
      ]
  
  postgres:
    image: "postgres:16-alpine"
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: pfun_cma_model_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pfun_cma_model_data:/var/lib/postgresql/data

volumes:
  pfun_cma_model_data:

secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
    file: .env