# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."pfun-cma-model" = {
    image = "localhost/compose2nix/pfun-cma-model";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    ports = [
      "8001:8001/tcp"
    ];
    cmd = [ "uv" "run" "uvicorn" "pfun_cma_model.app:app" "--proxy-headers" "--host" "0.0.0.0" "--port" "8001" "--workers" "2" ];
    dependsOn = [
      "pfun-cma-model-redis"
    ];
    user = "nonroot:nonroot";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=pfun-cma-model"
      "--network=pfun-cma-model_pfun-cma-network"
    ];
  };
  systemd.services."podman-pfun-cma-model" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    requires = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };
  virtualisation.oci-containers.containers."pfun-cma-model-redis" = {
    image = "redis:7-alpine";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    volumes = [
      "pfun-cma-model_redis-data:/data:rw"
    ];
    cmd = [ "redis-server" "--save" "60" "1" "--loglevel" "warning" "--maxmemory" "128mb" "--maxmemory-policy" "allkeys-lru" ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.5"
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=10s"
      "--health-retries=3"
      "--health-timeout=5s"
      "--memory=268435456b"
      "--network-alias=redis"
      "--network=pfun-cma-model_pfun-cma-network"
    ];
  };
  systemd.services."podman-pfun-cma-model-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
      "podman-volume-pfun-cma-model_redis-data.service"
    ];
    requires = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
      "podman-volume-pfun-cma-model_redis-data.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };
  virtualisation.oci-containers.containers."pfun-qt-gui" = {
    image = "localhost/pfun-qt-gui:latest";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    volumes = [
      "/home/robbiec/Git/pfun-cma-model/packages/pfun_qt_gui:/app:rw"
      "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ];
    user = "nonroot:nonroot";
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-pfun-qt-gui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-pfun-cma-model_pfun-cma-network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f pfun-cma-model_pfun-cma-network";
    };
    script = ''
      podman network inspect pfun-cma-model_pfun-cma-network || podman network create pfun-cma-model_pfun-cma-network --driver=bridge --subnet=172.20.0.0/16 --gateway=172.20.0.1
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-pfun-cma-model_redis-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect pfun-cma-model_redis-data || podman volume create pfun-cma-model_redis-data
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };

  # Builds
  systemd.services."podman-build-pfun-cma-model" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/pfun-cma-model
      podman build -t compose2nix/pfun-cma-model .
    '';
  };
  systemd.services."podman-build-pfun-qt-gui" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/pfun-cma-model/packages/pfun_qt_gui
      podman build -t pfun-qt-gui:latest .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-pfun-cma-model-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
