# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."pfun-cma-model" = {
    image = "localhost/compose2nix/pfun-cma-model";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    ports = [
      "8001:8001/tcp"
    ];
    cmd = [ "uv" "run" "uvicorn" "pfun_cma_model.app:app" "--proxy-headers" "--host" "0.0.0.0" "--port" "8001" "--workers" "1" ];
    user = "nonroot:nonroot";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=pfun-cma-model"
      "--network=pfun-cma-model_pfun-cma-network"
    ];
  };
  systemd.services."podman-pfun-cma-model" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    requires = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };
  virtualisation.oci-containers.containers."pfun-gradio" = {
    image = "localhost/compose2nix/pfun-gradio";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    ports = [
      "7860:7860/tcp"
    ];
    cmd = [ "uv" "run" "uvicorn" "pfun_gradio.main:app" "--proxy-headers" "--host" "0.0.0.0" "--port" "7860" "--workers" "1" ];
    user = "nonroot:nonroot";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=pfun-gradio"
      "--network=pfun-cma-model_pfun-cma-network"
    ];
  };
  systemd.services."podman-pfun-gradio" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    requires = [
      "podman-network-pfun-cma-model_pfun-cma-network.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ts-pfun" = {
    image = "pfun-health/tailscale-sidecar:latest";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    volumes = [
      "/dev/net/tun:/dev/net/tun:rw"
      "pfun-cma-model_ts-nginx-certs:/certs:rw"
      "pfun-cma-model_ts-nginx-state:/var/lib/tailscale:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=net_admin"
      "--cap-add=sys_module"
      "--hostname=pfun"
      "--network-alias=ts-nginx"
      "--network=pfun-cma-model_default"
    ];
  };
  systemd.services."podman-ts-pfun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pfun-cma-model_default.service"
      "podman-volume-pfun-cma-model_ts-nginx-certs.service"
      "podman-volume-pfun-cma-model_ts-nginx-state.service"
    ];
    requires = [
      "podman-network-pfun-cma-model_default.service"
      "podman-volume-pfun-cma-model_ts-nginx-certs.service"
      "podman-volume-pfun-cma-model_ts-nginx-state.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ts-pfun-nginx" = {
    image = "nginx:1.29-trixie";
    environmentFiles = [
      "/home/robbiec/Git/pfun-cma-model/.env"
    ];
    volumes = [
      "/home/robbiec/Git/pfun-cma-model/nginx/html/index.html:/etc/nginx/html/index.html:ro"
      "/home/robbiec/Git/pfun-cma-model/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      "pfun-cma-model_ts-nginx-certs:/certs:rw"
    ];
    dependsOn = [
      "pfun-cma-model"
      "pfun-gradio"
      "ts-pfun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"sh\", \"-c\", \"envsubst < /etc/nginx/nginx.conf && nginx -g 'daemon off;'\"]"
      "--network=container:ts-pfun"
    ];
  };
  systemd.services."podman-ts-pfun-nginx" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-pfun-cma-model_ts-nginx-certs.service"
    ];
    requires = [
      "podman-volume-pfun-cma-model_ts-nginx-certs.service"
    ];
    partOf = [
      "podman-compose-pfun-cma-model-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-cma-model-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-pfun-cma-model_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f pfun-cma-model_default";
    };
    script = ''
      podman network inspect pfun-cma-model_default || podman network create pfun-cma-model_default
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };
  systemd.services."podman-network-pfun-cma-model_pfun-cma-network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f pfun-cma-model_pfun-cma-network";
    };
    script = ''
      podman network inspect pfun-cma-model_pfun-cma-network || podman network create pfun-cma-model_pfun-cma-network --driver=bridge
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-pfun-cma-model_ts-nginx-certs" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect pfun-cma-model_ts-nginx-certs || podman volume create pfun-cma-model_ts-nginx-certs
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };
  systemd.services."podman-volume-pfun-cma-model_ts-nginx-state" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect pfun-cma-model_ts-nginx-state || podman volume create pfun-cma-model_ts-nginx-state
    '';
    partOf = [ "podman-compose-pfun-cma-model-root.target" ];
    wantedBy = [ "podman-compose-pfun-cma-model-root.target" ];
  };

  # Builds
  systemd.services."podman-build-pfun-cma-model" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/pfun-cma-model
      podman build -t compose2nix/pfun-cma-model .
    '';
  };
  systemd.services."podman-build-pfun-gradio" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/pfun-cma-model
      podman build -t compose2nix/pfun-gradio -f ./pfun_gradio/Dockerfile .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-pfun-cma-model-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
