[tool.poetry]
name = "pfun-cma-model"
version = "0.2.0"
description = "pfun cma model microservices"
authors = ["Robbie Capps <rocapp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
numpy = "^1.26.0"
pandas = "^2.1.1"
scikit-learn = "^1.3.1"
scipy = "^1.8.0"
seaborn = "^0.13.0"
matplotlib = "^3.8.0"
pydantic = "^2.4.2"
conda-lock = "^2.3.0"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytest = "^7.4.2"
opensearch-py = "^2.3.1"
openai = "^0.28.1"
tiktoken = "^0.5.1"
requests = "^2.31.0"
chalice = "^1.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
