[tool.poetry]
name = "pfun-cma-model"
version = "0.2.0"
description = ""
authors = ["Robbie Capps <rocapp@gmail.com>"]
readme = "README.md"
packages = [{include = "pfun_cma_model"}]

[tool.poetry.dependencies]
python = "~3.10"
numba = "^0.58.0"
numpy = ">=1.21,<1.26"
pandas = "^2.1.1"
scipy = "^1.11.3"
matplotlib = "^3.8.0"
opensearch-py = "^2.3.1"
pydantic = "2.4.2"
click = "^8.1.7"
paramiko = "^3.3.1"
pfun_path_helper = "^0.0.2"
boto3 = "^1.28.57"
botocore = "^1.31.57"
kubernetes = "^28.1.0"

[tool.poetry.group.dev.dependencies]
click = "^8.1.7"
pytest = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
