[tool.poetry]
name = "pfun-cma-model"
version = "0.2.0"
description = ""
authors = ["Robbie Capps <rocapp@gmail.com>"]
readme = "README.md"
packages = [{include = "pfun_cma_model"}]

[tool.poetry.dependencies]
python = "~3.10"
pandas = "^2.1.1"
opensearch-py = "^2.3.1"
pydantic = "2.4.2"
click = "^8.1.7"
paramiko = "^3.3.1"
pfun_path_helper = "^0.0.2"
boto3 = "^1.28.57"

[tool.poetry.group.dev.dependencies]
click = "^8.1.7"
pytest

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
