# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AlertRecord(BaseModel):
    """
    AlertRecord
    """ # noqa: E501
    record_id: Optional[StrictStr] = Field(default=None, alias="recordId")
    system_time: Optional[datetime] = Field(default=None, alias="systemTime")
    display_time: Optional[datetime] = Field(default=None, alias="displayTime")
    alert_name: Optional[StrictStr] = Field(default=None, alias="alertName")
    alert_state: Optional[StrictStr] = Field(default=None, alias="alertState")
    display_device: Optional[StrictStr] = Field(default=None, alias="displayDevice")
    transmitter_generation: Optional[StrictStr] = Field(default=None, alias="transmitterGeneration")
    transmitter_id: Optional[StrictStr] = Field(default=None, alias="transmitterId")
    __properties: ClassVar[List[str]] = ["recordId", "systemTime", "displayTime", "alertName", "alertState", "displayDevice", "transmitterGeneration", "transmitterId"]

    @field_validator('alert_name')
    def alert_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unknown', 'high', 'low', 'rise', 'fall', 'outOfRange', 'urgentLow', 'urgentLowSoon', 'noReadings', 'fixedLow']):
            raise ValueError("must be one of enum values ('unknown', 'high', 'low', 'rise', 'fall', 'outOfRange', 'urgentLow', 'urgentLowSoon', 'noReadings', 'fixedLow')")
        return value

    @field_validator('alert_state')
    def alert_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unknown', 'inactive', 'activeSnoozed', 'activeAlarming']):
            raise ValueError("must be one of enum values ('unknown', 'inactive', 'activeSnoozed', 'activeAlarming')")
        return value

    @field_validator('transmitter_generation')
    def transmitter_generation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unknown', 'g4', 'g5', 'g6', 'g6+', 'dexcomPro', 'g7']):
            raise ValueError("must be one of enum values ('unknown', 'g4', 'g5', 'g6', 'g6+', 'dexcomPro', 'g7')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recordId": obj.get("recordId"),
            "systemTime": obj.get("systemTime"),
            "displayTime": obj.get("displayTime"),
            "alertName": obj.get("alertName"),
            "alertState": obj.get("alertState"),
            "displayDevice": obj.get("displayDevice"),
            "transmitterGeneration": obj.get("transmitterGeneration"),
            "transmitterId": obj.get("transmitterId")
        })
        return _obj


