# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.exchange_authorization_code200_response import ExchangeAuthorizationCode200Response

class TestExchangeAuthorizationCode200Response(unittest.TestCase):
    """ExchangeAuthorizationCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeAuthorizationCode200Response:
        """Test ExchangeAuthorizationCode200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeAuthorizationCode200Response`
        """
        model = ExchangeAuthorizationCode200Response()
        if include_optional:
            return ExchangeAuthorizationCode200Response(
                access_token = '',
                expires_in = 56,
                token_type = '',
                refresh_token = ''
            )
        else:
            return ExchangeAuthorizationCode200Response(
        )
        """

    def testExchangeAuthorizationCode200Response(self):
        """Test ExchangeAuthorizationCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
