# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_data_range200_response import GetDataRange200Response

class TestGetDataRange200Response(unittest.TestCase):
    """GetDataRange200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDataRange200Response:
        """Test GetDataRange200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDataRange200Response`
        """
        model = GetDataRange200Response()
        if include_optional:
            return GetDataRange200Response(
                record_type = '',
                record_version = '',
                user_id = '',
                calibrations = openapi_client.models.get_data_range_200_response_calibrations.getDataRange_200_response_calibrations(
                    start = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    end = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), ),
                egvs = openapi_client.models.get_data_range_200_response_calibrations.getDataRange_200_response_calibrations(
                    start = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    end = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), ),
                events = openapi_client.models.get_data_range_200_response_calibrations.getDataRange_200_response_calibrations(
                    start = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    end = openapi_client.models.data_range_moment.DataRangeMoment(
                        system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return GetDataRange200Response(
        )
        """

    def testGetDataRange200Response(self):
        """Test GetDataRange200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
