# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_exchange_authorization_code(self) -> None:
        """Test case for exchange_authorization_code

        """
        pass

    def test_get_alerts(self) -> None:
        """Test case for get_alerts

        """
        pass

    def test_get_calibrations(self) -> None:
        """Test case for get_calibrations

        """
        pass

    def test_get_data_range(self) -> None:
        """Test case for get_data_range

        """
        pass

    def test_get_devices_v3(self) -> None:
        """Test case for get_devices_v3

        """
        pass

    def test_get_estimated_glucose_values(self) -> None:
        """Test case for get_estimated_glucose_values

        """
        pass

    def test_get_events_v3(self) -> None:
        """Test case for get_events_v3

        """
        pass

    def test_user_authorization(self) -> None:
        """Test case for user_authorization

        """
        pass


if __name__ == '__main__':
    unittest.main()
