# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.egv_record import EGVRecord

class TestEGVRecord(unittest.TestCase):
    """EGVRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EGVRecord:
        """Test EGVRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EGVRecord`
        """
        model = EGVRecord()
        if include_optional:
            return EGVRecord(
                record_id = '',
                system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                transmitter_id = '',
                transmitter_ticks = 56,
                value = 56,
                status = 'unknown',
                trend = 'none',
                trend_rate = 1.337,
                unit = 'unknown',
                rate_unit = 'unknown',
                display_device = '',
                transmitter_generation = 'unknown'
            )
        else:
            return EGVRecord(
        )
        """

    def testEGVRecord(self):
        """Test EGVRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
