# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.alert_record import AlertRecord

class TestAlertRecord(unittest.TestCase):
    """AlertRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertRecord:
        """Test AlertRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertRecord`
        """
        model = AlertRecord()
        if include_optional:
            return AlertRecord(
                record_id = '',
                system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                alert_name = 'unknown',
                alert_state = 'unknown',
                display_device = '',
                transmitter_generation = 'unknown',
                transmitter_id = ''
            )
        else:
            return AlertRecord(
        )
        """

    def testAlertRecord(self):
        """Test AlertRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
