# coding: utf-8

"""
    Dexcom Developer API

    This API provides access to Dexcom continuous glucose monitoring data for authorized users.

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_data_range200_response_calibrations import GetDataRange200ResponseCalibrations

class TestGetDataRange200ResponseCalibrations(unittest.TestCase):
    """GetDataRange200ResponseCalibrations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDataRange200ResponseCalibrations:
        """Test GetDataRange200ResponseCalibrations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDataRange200ResponseCalibrations`
        """
        model = GetDataRange200ResponseCalibrations()
        if include_optional:
            return GetDataRange200ResponseCalibrations(
                start = openapi_client.models.data_range_moment.DataRangeMoment(
                    system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                end = openapi_client.models.data_range_moment.DataRangeMoment(
                    system_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    display_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetDataRange200ResponseCalibrations(
        )
        """

    def testGetDataRange200ResponseCalibrations(self):
        """Test GetDataRange200ResponseCalibrations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
