version: '3'
services:
  tflocal:
    image: rocapp222/tflocal:latest
    depends_on:
      - nginx
    ports:
      - "8080:8080"
    expose: [8080]
    environment:
      AWS_PROFILE: "localstack"
      LOCALSTACK_HOSTNAME: "nginx"
      EDGE_PORT: "8080"
    env_file: 
      - .envrc
    volumes:
      - ./awslocal:/.aws:ro
      - .:/workspace
    working_dir: /workspace
    links:
      - nginx
    networks:
      - host
  nginx:
    image: nginx
    ports:
      - "8080:8080"
      - "4566:4566"
      - "31566:31566"
    expose: [4566, 31566, 8080]
    volumes:
      - ~/Git/pfun-cma-model/runtime/localstack-package/nginx-localstack.conf:/etc/nginx/sites-enabled/nginx-localstack.conf:ro
      - ./certs:/etc/nginx/certs
    networks:
      - host
    hostname: localhost.localstack.cloud
networks:
  host:
