worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        location /auth {
            # tailscale nginx authentication
            # ref: https://tailscale.com/blog/tailscale-auth-nginx
            internal;

            proxy_pass http://unix:/run/tailscale.nginx-auth.sock;
            proxy_pass_request_body off;

            proxy_set_header Host $http_host;
            proxy_set_header Remote-Addr $remote_addr;
            proxy_set_header Remote-Port $remote_port;
            proxy_set_header Original-URI $request_uri;
            # # uncomment below to restrict access to a specific tailnet
            ###proxy_set_header Expected-Tailnet "tailnet012345.ts.net";
        }

        location / {
            proxy_pass http://$remote_addr:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # CORS headers
            add_header 'Access-Control-Allow-Origin' 'localhost, robcapps.com, cloud.tail38611b.ts.net, pfun.one, pfun.me, pfun.run, pfun.app';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type';

            # tailscale nginx auth configuration
            auth_request /auth;
            auth_request_set $auth_user $upstream_http_tailscale_user;
            auth_request_set $auth_name $upstream_http_tailscale_name;
            auth_request_set $auth_login $upstream_http_tailscale_login;
            auth_request_set $auth_tailnet $upstream_http_tailscale_tailnet;
            auth_request_set $auth_profile_picture $upstream_http_tailscale_profile_picture;

            proxy_set_header X-Webauth-User "$auth_user";
            proxy_set_header X-Webauth-Name "$auth_name";
            proxy_set_header X-Webauth-Login "$auth_login";
            proxy_set_header X-Webauth-Tailnet "$auth_tailnet";
            proxy_set_header X-Webauth-Profile-Picture "$auth_profile_picture";

            # Additional settings
            proxy_read_timeout 90;
            proxy_connect_timeout 90;
            proxy_redirect off;

            # Disable buffering for streaming responses
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}