# ssl-params.conf
# Extra configuration options for SSL
# Disable older (not secure) TLS protocol versions.
ssl_protocols        TLSv1.3;
ssl_prefer_server_ciphers on;
# Enable SSL session cache
# ref: https://linuxblog.io/nginx-tuning-tips-tls-ssl-https-ttfb-latency/
ssl_session_cache shared:SSL:1m; # holds approx 4000 sessions
ssl_session_timeout 1h; # 1 hour during which sessions can be re-used.
# Use ssl session tickets
ssl_session_tickets on;
# Reduce SSL buffer size (reduce time to first byte)
ssl_buffer_size 4k;
# Enable HTTP strict transport security (HSTS)
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
# Extra security headers
add_header X-Frame-Options sameorigin;
add_header X-Content-Type-Options nosniff;
add_header X-Xss-Protection "1; mode=block";