services:
  
  pfun-qt-gui:
    labels:
      - "compose2nix.settings.sops.secrets=.env"
    user: "nonroot:nonroot"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - USER=nonroot
      - GROUP=nonroot
    build:
      context: .
      dockerfile: Dockerfile
    image: pfun-qt-gui:latest
    container_name: pfun-qt-gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    network_mode: host
    restart: unless-stopped
