# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."pfun-qt-gui" = {
    image = "localhost/pfun-qt-gui:latest";
    environment = {
      "DISPLAY" = ":0";
      "GROUP" = "nonroot";
      "QT_X11_NO_MITSHM" = "1";
      "USER" = "nonroot";
    };
    volumes = [
      "/home/robbiec/Git/pfun-cma-model/packages/pfun_qt_gui:/app:rw"
      "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ];
    cmd = [ "./scripts/launch-qt-gui.sh" ];
    user = "nonroot:nonroot";
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-pfun-qt-gui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-pfun-qt-gui-root.target"
    ];
    wantedBy = [
      "podman-compose-pfun-qt-gui-root.target"
    ];
  };

  # Builds
  systemd.services."podman-build-pfun-qt-gui" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/pfun-cma-model/packages/pfun_qt_gui
      podman build -t pfun-qt-gui:latest .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-pfun-qt-gui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
